CREATE TABLE INSTRUCTOR (
  idINSTRUCTOR INTEGER  NOT NULL,
  NOMBRE TEXT NULL,
  CEDULA TEXT NULL,
  ESTADO INTEGER UNSIGNED NULL,
  PRIMARY KEY(idINSTRUCTOR)
);

CREATE TABLE FICHA (
  idFICHA INTEGER  NOT NULL,
  NOMFICHA TEXT NULL,
  PRIMARY KEY(idFICHA)
);

CREATE TABLE APRENDIZ (
  idAPRENDIZ INTEGER  NOT NULL,
  idFICHA INTEGER  NOT NULL,
  NOMBRE TEXT NULL,
  DNI TEXT NULL,
  PWD TEXT NUL,
  CORREO TEXT NULL,
  PRIMARY KEY(idAPRENDIZ, idFICHA),
  UNIQUE(CORREO)
  
);

CREATE TABLE "FICHAINSTRUCTOR" (
	"idFICHA"	INTEGER NOT NULL,
	"idINSTRUCTOR"	INTEGER NOT NULL,
	PRIMARY KEY("idFICHA","idINSTRUCTOR")
	);

CREATE TABLE THEVAL (
  idTHEVAL INTEGER  NOT NULL ,
  idINSTRUCTOR INTEGER  NOT NULL,
  idFICHA INTEGER  NOT NULL,
  idAPRENDIZ INTEGER  NOT NULL,
  PREGUNTA INTEGER  NULL,
  RESPUESTA TEXT NULL,
  PRIMARY KEY(idTHEVAL),
  FOREIGN KEY(idAPRENDIZ, idFICHA)
    REFERENCES APRENDIZ(idAPRENDIZ, idFICHA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(idFICHA, idINSTRUCTOR)
    REFERENCES FICHAINSTRUCTOR(idFICHA, idINSTRUCTOR)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE VIEW VMOSTRAR AS
SELECT T.IDFICHA,
I.IDINSTRUCTOR, 
A.IDAPRENDIZ,
I.NOMBRE INSTRUCTOR,
A.NOMBRE APRENDIZ,
F.NOMFICHA FICHA,
A.DNI DNI_APRENDIZ,
I.CEDULA DNI_INSTRUCTOR
FROM THEVAL T
JOIN INSTRUCTOR I
USING(IDINSTRUCTOR)
JOIN FICHA F
ON F.idFICHA=T.idFICHA
JOIN APRENDIZ A
ON A.IDAPRENDIZ=T.idAPRENDIZ;


