CREATE TABLE INSTRUCTOR (
  idINSTRUCTOR INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NOMBRE TEXT NULL,
  CEDULA TEXT NULL,
  ESTADO INTEGER UNSIGNED NULL,
  PRIMARY KEY(idINSTRUCTOR)
);

CREATE TABLE FICHA (
  idFICHA INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  NOMFICHA TEXT NULL,
  PRIMARY KEY(idFICHA)
);

CREATE TABLE APRENDIZ (
  idAPRENDIZ INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  idFICHA INTEGER UNSIGNED NOT NULL,
  NOMBRE TEXT NULL,
  DNI TEXT NULL,
  PWD TEXT NULL,
  CORREO TEXT NULL,
  PRIMARY KEY(idAPRENDIZ, idFICHA),
  INDEX APRENDIZ_FKIndex1(idFICHA),
  UNIQUE INDEX CORREO_index1706(CORREO),
  FOREIGN KEY(idFICHA)
    REFERENCES FICHA(idFICHA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE FICHAINSTRUCTOR (
  idFICHA INTEGER UNSIGNED NOT NULL,
  idINSTRUCTOR INTEGER UNSIGNED NOT NULL,
  PRIMARY KEY(idFICHA, idINSTRUCTOR),
  INDEX FICHA_has_INSTRUCTOR_FKIndex1(idFICHA),
  INDEX FICHA_has_INSTRUCTOR_FKIndex2(idINSTRUCTOR),
  FOREIGN KEY(idFICHA)
    REFERENCES FICHA(idFICHA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(idINSTRUCTOR)
    REFERENCES INSTRUCTOR(idINSTRUCTOR)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);

CREATE TABLE THEVAL (
  idTHEVAL INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  idINSTRUCTOR INTEGER UNSIGNED NOT NULL,
  idFICHA INTEGER UNSIGNED NOT NULL,
  idAPRENDIZ INTEGER UNSIGNED NOT NULL,
  PREGUNTA INTEGER UNSIGNED NULL,
  RESPUESTA TEXT NULL,
  PRIMARY KEY(idTHEVAL),
  INDEX THEVAL_FKIndex2(idAPRENDIZ, idFICHA),
  INDEX THEVAL_FKIndex2(idFICHA, idINSTRUCTOR),
  FOREIGN KEY(idAPRENDIZ, idFICHA)
    REFERENCES APRENDIZ(idAPRENDIZ, idFICHA)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION,
  FOREIGN KEY(idFICHA, idINSTRUCTOR)
    REFERENCES FICHAINSTRUCTOR(idFICHA, idINSTRUCTOR)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
);


